### ISSUE TITLE
How to reload the Ads

### ISSUE THREAD

**Issue by rabichawila** [mazipan/vue-google-adsense#11]
Thank you very much for this awesome **repo**. 👍 

But i have this ads on my side navigation which does not change across the entire website,
(because i only update the middle content with **vue-resource** )

so i'll really like to know how i can reload that Ads.
which is written in official Google doc | [Reload ads without a page refresh](https://support.google.com/admanager/answer/2694377?hl=en)   

i hope u understand..

**Comment by mazipan** [comment]
I know what you mean, thanks for using this library.
After reading the reference material, I think it's different scope with Google Ads.
Because it's get different script cdn and also doing different thing with Google Ads.

But from me, you can do that thing with library `script2` that I also use in this library or you can insert in your HTML just like in the docs.

**Comment by jamiecarter7** [comment]
I think you can add a key="" then you can increase the key value by one to refresh the advert
