### ISSUE TITLE
Attribute is not applied to the ins tag

### ISSUE THREAD

**Issue by 158008001** [mazipan/vue-google-adsense#45]
Final effect screenshot:
![Snipaste_2019-08-25_00-33-06](https://user-images.githubusercontent.com/32694319/63640201-0ae83c80-c6d0-11e9-9077-014389da968b.png)

The results of the following two methods are displayed on the root element:
`data-full-width-responsive="true"`
`:data-full-width-responsive="true"`

Or, my operation is wrong?   -, -

**Comment by mazipan** [comment]
Can not reproduce

**Comment by vesper8** [comment]
I can certainly reproduce it @mazipan ! 

in my case applying

```
:data-full-width-responsive="false"
```

Causes the data-full-wdith-responsive to be completely missing, thus defaulting to "true" and making my ads appear much larger than I intend for them to be.

The way to make it work is to pass the boolean as a string like so:

```
:data-full-width-responsive="'false'"
```

Notice the extra single quotes

I imagine the same applies to `true`

This is probably occuring because of
```
dataFullWidthResponsive: {
    type: Boolean,
    default: false
  }
```

? It should be set to a string instead.. or it should be cast as a string

You probably didn't notice this because you've been happy with all your ads being "responsive" all this time

**Comment by vesper8** [comment]
I imagine the `is-non-personalized-ads` is probably non-working as well for the same reason, though I can't test this because I don't use those types of ads

**Comment by mazipan** [comment]
Will change into string
